// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovinskaAgencija;

#nullable disable

namespace NovinskaAgencija.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230621160951_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NovinskaAgencija.data.model.Clanak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clanci");
                });

            modelBuilder.Entity("NovinskaAgencija.data.model.ClanakOblast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClanakId")
                        .HasColumnType("int");

                    b.Property<int>("OblastId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClanakId");

                    b.HasIndex("OblastId");

                    b.ToTable("ClanakOblast");
                });

            modelBuilder.Entity("NovinskaAgencija.data.model.Oblast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Oblasti");
                });

            modelBuilder.Entity("NovinskaAgencija.data.model.Placanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClanakId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClanakId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Placanja");
                });

            modelBuilder.Entity("NovinskaAgencija.data.model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForgotPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JurassicAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PassswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("StateOfOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NovinskaAgencija.data.model.UserClanak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClanakId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClanakId");

                    b.HasIndex("UserId");

                    b.ToTable("UserClanak");
                });

            modelBuilder.Entity("NovinskaAgencija.data.model.ClanakOblast", b =>
                {
                    b.HasOne("NovinskaAgencija.data.model.Clanak", "Clanak")
                        .WithMany("ClanakOblasti")
                        .HasForeignKey("ClanakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovinskaAgencija.data.model.Oblast", "Oblast")
                        .WithMany("ClanakOblasti")
                        .HasForeignKey("OblastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clanak");

                    b.Navigation("Oblast");
                });

            modelBuilder.Entity("NovinskaAgencija.data.model.Placanje", b =>
                {
                    b.HasOne("NovinskaAgencija.data.model.Clanak", "Clanak")
                        .WithOne("Placanje")
                        .HasForeignKey("NovinskaAgencija.data.model.Placanje", "ClanakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovinskaAgencija.data.model.User", "User")
                        .WithMany("Placanja")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clanak");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NovinskaAgencija.data.model.UserClanak", b =>
                {
                    b.HasOne("NovinskaAgencija.data.model.Clanak", "Clanak")
                        .WithMany("UserClanci")
                        .HasForeignKey("ClanakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovinskaAgencija.data.model.User", "User")
                        .WithMany("UserClanci")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clanak");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NovinskaAgencija.data.model.Clanak", b =>
                {
                    b.Navigation("ClanakOblasti");

                    b.Navigation("Placanje")
                        .IsRequired();

                    b.Navigation("UserClanci");
                });

            modelBuilder.Entity("NovinskaAgencija.data.model.Oblast", b =>
                {
                    b.Navigation("ClanakOblasti");
                });

            modelBuilder.Entity("NovinskaAgencija.data.model.User", b =>
                {
                    b.Navigation("Placanja");

                    b.Navigation("UserClanci");
                });
#pragma warning restore 612, 618
        }
    }
}
